services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    networks:
      - Front_End
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /opt/docker/Homelab_Docker_Config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
#    If needed to run docker container as different user
#    environment:
#      PUID: $PUID
#      PGID: $PGID

networks:
  Front_End:
    name: Front_End
    driver: bridge
