---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Infrastructure (Seattle):
    style: row
    columns: 4
  Media:
    style: column
  Applications:
    style: column
